version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - auth-service
      - cinema-service
      - public-service
      - frontend-app
    networks:
      - cinema-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_URL=http://auth-service:3001
      - CINEMA_SERVICE_URL=http://cinema-service:3002
      - PUBLIC_SERVICE_URL=http://public-service:3003
    networks:
      - cinema-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cinema_auth
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=votre_secret_jwt
    depends_on:
      - postgres
    networks:
      - cinema-network

  cinema-service:
    build:
      context: ./cinema-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cinema_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - cinema-network

  public-service:
    build:
      context: ./public-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cinema_public
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - cinema-network

  frontend-app:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost/api
    networks:
      - cinema-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=cinema_auth,cinema_db,cinema_public
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge

volumes:
  postgres_data: 